Configuration Type	Configuration Name	HRL available?	File Name is correct in export sheet?	Exported?	Imported?	
ServiceCategory	BRDENELEV	HRL Found				C:\1\ServiceCategory\ServiceCategory.BRDENELEV.1800-01-01.a.hrl
ServiceCategory	BRDENESA	HRL Found				C:\1\ServiceCategory\ServiceCategory.BRDENESA.1800-01-01.a.hrl
ServiceCategory	Speech Therapy	HRL Found				C:\1\ServiceCategory\ServiceCategory.SpeechTherapy.1800-01-01.a.hrl
ServiceCategory	Physical and Occupational Therapy	HRL Found				C:\1\ServiceCategory\ServiceCategory.PhysicalandOccupationalTherapy.1800-01-01.a.hrl
ServiceCategory	Occupational Therapy	HRL Found				C:\1\ServiceCategory\ServiceCategory.OccupationalTherapy.1800-01-01.a.hrl
ServiceCategory	Medical Services - Medicare	HRL Found				C:\1\ServiceCategory\ServiceCategory.MedicalServices-Medicare.1800-01-01.a.hrl
ServiceCategory	Landmark Provider Cost Share Waiver	HRL Found				C:\1\ServiceCategory\ServiceCategory.LandmarkProviderCostShareWaiver.2025-01-01.a.hrl
ServiceCategory	BRADOFFOOT	HRL Found				C:\1\ServiceCategory\ServiceCategory.BRADOFFOOT.1800-01-01.a.hrl
ServiceCategory	Routine Foot Care - Pend	HRL Found				C:\1\ServiceCategory\ServiceCategory.RoutineFootCare-Pend.1800-01-01.a.hrl
ServiceCategory	Medical Supplies - Compression Garments - Medicare Covered	HRL Found				C:\1\ServiceCategory\ServiceCategory.MedicalSupplies-CompressionGarments-MedicareCovered.1800-01-01.a.hrl
ServiceCategory	Medical Supplies - Compression Garments - NMC	HRL Found				C:\1\ServiceCategory\ServiceCategory.MedicalSupplies-CompressionGarments-NMC.1800-01-01.a.hrl
ServiceCategory	Compression - MC Diagnosis	HRL Found				C:\1\ServiceCategory\ServiceCategory.Compression-MCDiagnosis.1800-01-01.a.hrl
ServiceCategory	Compression - NMC Diagnosis 					
BenefitPlanComponent	Dental - Exchange - Medical - Exclusion	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.Dental-Exchange-Medical-Exclusion.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN - ISNP (Coinsurance Deductible Waived) PCP (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN-ISNP_CoinsuranceDeductibleWaived_PCP_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Benefit Specific Coinsurance Deductible Waived) PCP (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_BenefitSpecificCoinsuranceDeductibleWaived_PCP_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Benefit Specific Coinsurance Deductible Waived) PCP (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_BenefitSpecificCoinsuranceDeductibleWaived_PCP_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Benefit Specific Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_BenefitSpecificCoinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Benefit Specific Coinsurance) PCP (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_BenefitSpecificCoinsurance_PCP_Copay.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance Deductible Waived) PCP (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_CoinsuranceDeductibleWaived_PCP_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance Deductible Waived) PCP (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_CoinsuranceDeductibleWaived_PCP_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Coinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance) PCP (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Coinsurance_PCP_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance) PCP (Benefit Specific Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Coinsurance_PCP_BenefitSpecificCoinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance) PCP (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Coinsurance_PCP_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Coinsurance) PCP (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Coinsurance_PCP_Copay.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - INN (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-INN_Copay.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Benefit Specific Coinsurance Deductible Waived) PCP (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_BenefitSpecificCoinsuranceDeductibleWaived_PCP_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Benefit Specific Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_BenefitSpecificCoinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Benefit Specific Coinsurance) PCP (Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_BenefitSpecificCoinsurance_PCP_Coinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance Deductible Waived) PCP (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_CoinsuranceDeductibleWaived_PCP_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance Deductible Waived) PCP (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_CoinsuranceDeductibleWaived_PCP_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Coinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance) PCP (Benefit Specific Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Coinsurance_PCP_BenefitSpecificCoinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Coinsurance) PCP (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Coinsurance_PCP_Copay.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Copay Deductible Waived) PCP (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_CopayDeductibleWaived_PCP_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Copay.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Copay) PCP (Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Copay_PCP_Coinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare - OON (Copay) PCP (Not Covered)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare-OON_Copay_PCP_NotCovered.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare (Alternate Office & Clinic Definition) - INN (Coinsurance Deductible Waived) Office (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare_AlternateOffice_and_ClinicDefinition_-INN_CoinsuranceDeductibleWaived_Office_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare (Alternate Office & Clinic Definition) - INN (Coinsurance) Office (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare_AlternateOffice_and_ClinicDefinition_-INN_Coinsurance_Office_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Services - Medicare (Alternate Office & Clinic Definition) - OON (Coinsurance) Office (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalServices-Medicare_AlternateOffice_and_ClinicDefinition_-OON_Coinsurance_Office_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Benefit Specific Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_BenefitSpecificCoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Benefit Specific Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_BenefitSpecificCoinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Coinsurance Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_CoinsuranceDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Coinsurance)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_Coinsurance.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Copay Deductible Waived)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_CopayDeductibleWaived.1800-01-01.a.hrl
BenefitPlanComponent	Medical Supplies - Compression Garments - Medicare Covered - INN (Copay)	HRL Found				C:\1\BenefitPlanComponent\BenefitPlanComponent.MedicalSupplies-CompressionGarments-MedicareCovered-INN_Copay.1800-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H0523-072 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H0523-072V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-001 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-001V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-002 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-002V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-004 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-004V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-007 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-007V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-017 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-017V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - POS - Medicare (AET) H4982-018 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-POS-Medicare_AET_H4982-018V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - PPO - Medicare (AET) H5521-419 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-PPO-Medicare_AET_H5521-419V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - PPO - Medicare (AET) H5521-421 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-PPO-Medicare_AET_H5521-421V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - PPO - Medicare (AET) H5521-422 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-PPO-Medicare_AET_H5521-422V1.2025-01-01.a.hrl
BenefitPlanTemplate	CA - PPO - Medicare (AET) H5521-425 V1	HRL Found				C:\1\BenefitPlanTemplate\BenefitPlanTemplate.CA-PPO-Medicare_AET_H5521-425V1.2025-01-01.a.hrl
